config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'users/show'
  devise_for :users
  root to: 'homes#top'
  get "home/about" => "homes#about"
  get "search" => "searchs#search"
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]

   resources :books, only: [:new, :create, :index, :show, :destroy, :update, :edit] do
       resource :favorites, only: [:create, :destroy]
       resources :book_comments, only: [:create, :destroy]
    #   get 'search'
   end

   resources :users, only: [:index, :show, :edit, :update, :create] do
        resource :relationships, only: [:create, :destroy]
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
        # get 'search' => 'users#search'
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book .find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    @book_comment = BookComment.new
    # binding.pry

    @comment.save
    # binding.pry
    # redirect_to book_path(book)
  end

  def destroy
    @book = Book .find(params[:book_id])
    @comments = BookComment.where(book_id: @book.id)
    @book_comment = BookComment.new
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    # redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comments.html.erb
  <p>コメント件数：<%= comments.count %></p>
    <% comments.each do |book_comment| %>
    <%#= image_tag('sample-author1.jpg') %>
    <%= attachment_image_tag user, :profile_image_id, size: "50x50", fallback: "no_image.jpg"%>
    <%= user.name %>
    <%= book_comment.created_at.strftime('%Y/%m/%d') %>
    <p>コメント:<%= book_comment.comment %> </p>
    <% if book_comment.user == current_user %>
    <div class="comment-delete">
      <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class:"btn btn-danger" %>
    </div>
     <% end %>
    <% end %>
    <div class="new-comment">
     <%= form_with(model:[book, book_comment], remote: true) do |f| %>
     <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
     <%= f.submit "送信する" %>
    <% end %>
<%#= render partial: "book_comments/comments", locals: { book: @book, user: @user, book_comment: @book_comment } %>

app/views/book_comments/create.js.erb
$('#comments_<%= @book.id %>').html("<%= j(render partial: 'book_comments/comments', locals: {book: @book, user: @book.user, book_comment: @book_comment, comments: @comment.book.book_comments }) %>");
$("textarea").val('')

app/views/book_comments/destroy.js.erb
$('#comments_<%= @book.id %>').html("<%= j(render partial: 'book_comments/comments', locals: {book: @book, user: @book.user, book_comment: @book_comment,comments:@comments}) %>");
<!--部分テンプレートの変数は全てここに入れる-->
<!--なぜなら非同期通信でこっちのコントローラとViewだけで動いてるから-->