config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'users/show'
  devise_for :users
  root to: 'homes#top'
  get "home/about" => "homes#about"
  get "search" => "searchs#search"
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]

   resources :books, only: [:new, :create, :index, :show, :destroy, :update, :edit] do
       resource :favorites, only: [:create, :destroy]
       resources :book_comments, only: [:create, :destroy]
    #   get 'search'
   end

   resources :users, only: [:index, :show, :edit, :update, :create] do
        resource :relationships, only: [:create, :destroy]
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
        # get 'search' => 'users#search'
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
   belongs_to :user, optional: true
   has_many :book_comments, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :favorited_users, through: :favorites, source: :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  is_impressionable counter_cache: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


  def self.search(search)
    if search
      Book.where('title LIKE(?)', "%#{search}%")
    #   Book.where('title LIKE(?)', 'body LIKE(?)', "%#{search}%")
    else
      Book.all
    end
  end


end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end
# a

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms  #1つのルームにいるユーザ数は2人のためhas_manyになる
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
   has_many :favorited_books, through: :favorites, source: :book

 has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
 has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人
 has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
 has_many :followings, through: :relationships, source: :followed

 has_many :user_rooms, dependent: :destroy
 has_many :chats, dependent: :destroy
  # ここから下↓はもしかしたらいらんかも↓
    def follow(user_id)
      relationships.create(followed_id: user_id)
    end

    def unfollow(user_id)
      relationships.find_by(followed_id: user_id).destroy
    end

    def following?(user)
      followings.include?(user)
    end

# ↓これ多分使わんから消していい
    # ユーザーをフォローする
# def follow(user_id)
#   follower.create(followed_id: user_id)
# end

# # ユーザーのフォローを外す
# def unfollow(user_id)
#   follower.find_by(followed_id: user_id).destroy
# end

# フォローしていればtrueを返す
# def following?(user)
#   followings.include?(user)
# end
 # ここまでいらんやつかも

 def self.search(search)
    if search
      User.where('name LIKE(?)', "%#{search}%")
    else
      User.all
    end
 end


  attachment :profile_image

  validates :name, presence: true, length: { minimum: 2,  maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
end

app/models/user_list.rb
class UserList < ApplicationRecord
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    # 回答にあった記載↓
    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day
    # @books = Book.includes(:favorited_users).sort {|a,b| b.favorited_users.where(created_at: from...to).size <=> a.favorited_users.where(created_at: from...to).size }
    @books = Book.includes(:favorited_users).sort {|a,b| b.favorited_users.where(created_at: from...to).size <=> a.favorited_users.where(created_at: from...to).size}
    # これやと並び替えはできる
    # ってことはここに「過去１週間のデータで」って入れられたらうまくいく？？

# 余裕できたら応用課題の質問する

    @user = current_user
    @book = Book.new
    # @ranks = Book.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}

  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    # @users = User.all
    @newbook = Book.new
    @book_comment = BookComment.new
    @comments = @book.book_comments
    # impressionist(@book, nil, unique: [:ip_address])
  end

  def new
    @book = Book.new
  end

  def create
     @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="You have creatad book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body,:impressions_count)
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

 def show
  @user = User.find(params[:id])
  rooms = current_user.user_rooms.pluck(:room_id)
  user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

  if user_rooms.nil?
   @room = Room.new
   @room.save
   UserRoom.create(user_id: @user.id, room_id: @room.id)
   UserRoom.create(user_id: current_user.id, room_id: @room.id)
  else
   @room = user_rooms.room
  end

  @chats = @room.chats
  @chat = Chat.new(room_id: @room.id)
 end

 def create
  @chat = current_user.chats.new(chat_params)
  @chat.save
 end

 private

 def chat_params
  params.require(:chat).permit(:message, :room_id)
 end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}
    # @bookfind = Book.find(params[:id])
 end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def create
    @book = Book.new(book_params)
    # @book.user_id = current_user.id
    @book.save
    redirect_to books_path
  end

  def search
    @users = User.search(params[:keyword])
    @book = Book.search(params[:keyword])
  end



  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_books.html.erb
<table class="table table-hover table-inverse">
<thead>
 <tr>
   <th></th>
   <th>Title</th>
   <th>Opinion</th>
   <th></th>
   <th></th>
   <!--<th colspan="3"></th>-->
 </tr>
</thead>
<tbody>
 <% books.each do |book| %>
   <tr>
     <td>
       <%= link_to user_path(book.user) do %>
       <%= attachment_image_tag book.user, :profile_image_id, size: "50x50",fallback: "no_image.jpg"%>
       <% end %>
      </td>
     <td><%= link_to book.title, book_path(book.id) %></td>
    <td><%= book.body %></td>
    <td>
         <% if book.favorited_by?(current_user) %>
            <p>
              <%= link_to book_favorites_path(book), method: :delete do %>
                ♥<%= book.favorites.count %> いいね
              <% end %>
            </p>
            <% else %>
            <p>
              <%= link_to book_favorites_path(book), method: :post do %>
                ♡<%= book.favorites.count %> いいね
              <% end %>
            </p>
          <% end %>
    </td>
    <td><%= link_to "コメント数: #{book.book_comments.count}", book_path(book.id) %></td>
  </tr>
  <% end %>
   </tbody>
</table>

app/views/books/_newbook.html.erb
 <h1>New book</h1>

 <% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
      <%= form_with model: book, local:true do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>opinion</h4>
        <%= f.text_area :body %>
        <div>
          <%= f.submit 'Create Book' %>
        </div>
    <% end %>

app/views/books/_rank.html.erb
<!--別リンクでいいね順で表示しようとしたページ-->

<tbody>
         <% books.each do |book| %>
           <tr>
             <td>
               <%= link_to user_path(book.user) do %>
               <%= attachment_image_tag book.user, :profile_image_id, size: "50x50",fallback: "no_image.jpg"%>
               <% end %>
              </td>
             <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
            <td id ="favorite_botton_<%= book.id %>">
                 <%= render partial: "favorites/favorites", locals: { book: book } %>
            </td>
            <td><%= link_to "コメント数: #{book.book_comments.count}", book_path(book.id) %></td>
          </tr>
          <% end %>
           </tbody>
        </table>
      </div>
    </div>
</div>

app/views/books/edit.html.erb
<div class="mx-auto" style="width: 300px;">
  <div class="col-xs-offset-3 col-xs-6">
      <h1>Editing Book</h1>
    <% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
          <%= form_with model: @book, local: true do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>opinion</h4>
        <%= f.text_area :body %>
        <div class="editbo">
          <%= f.submit 'Update Book' %>
          <% end %>
        </div>

          <div class="menu">
            <%= link_to "Show", book_path(@book) %>
            |
            <%= link_to "Back", books_path %>
          </div>
    </div>
  </div>

app/views/books/index.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-3">
          <%= render 'users/info', user: @user %>
          <%= render 'books/newbook', book: @book %>
       </div>

        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
        <thead>
         <tr>
           <th></th>
           <th>Title</th>
           <th>Opinion</th>
           <th></th>
           <th></th>
           <th></th>
         </tr>
       </thead>
       <tbody>
         <% @books.each do |book| %>
           <tr>
             <td>
               <%= link_to user_path(book.user) do %>
               <%= attachment_image_tag book.user, :profile_image_id, size: "50x50",fallback: "no_image.jpg"%>
               <% end %>
              </td>
             <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
            <td id ="favorite_botton_<%= book.id %>">
                 <%= render partial: "favorites/favorites", locals: { book: book } %>
            </td>
            <td><%= link_to "コメント数: #{book.book_comments.count}", book_path(book.id) %></td>
            <td>
             <% @books.each do |t| %>
               <%= t.impressions_count %>
              <% end %>
            </td>
          </tr>
          <% end %>
           </tbody>
        </table>
      </div>
    </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_with model: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'CreateBook' %>
<% end %>

app/views/books/show.html.erb
 <%#= flash[:notice] %>
<div class="container">
     <div class="row">
       <div class="col-md-3">
          <%= render 'users/info', user: @user %>
          <%= render 'books/newbook', book: @newbook %>
       </div>

        <div class="col-md-8 offset-md-1">
          <h1>Book detail</h1>
          <table class="table table-user-show">
            <tr>
              <td><%= attachment_image_tag @user, :profile_image_id, size: "50x50", fallback: "no_image.jpg"%></td>
              <td><%= link_to @user.name, user_path(@user) %></td>
              <td><%= @book.title %></td>
              <td><%= @book.body %></td>
              <% if @book.user.id == current_user.id %>
                <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-success"%></td>
                <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger" %></td>
              <% end %>
            </tr>
          </table>
            <div id ="favorite_botton_<%= @book.id %>">
                 <%= render partial: "favorites/favorites", locals: { book: @book } %>
            </div>

              <div id="comments_<%= @book.id %>">
                <%= render partial: "book_comments/comments", locals: { book: @book, user: @user, book_comment: @book_comment, comments: @comments} %>
              </div>
        </div>
    </div>
</div>

app/views/chats/create.js.erb
$('.message').append("<p style='text-align: left;'><%= @chat.message %></p>");
/*チャット投稿後、フォームの値に前回の投稿内容が残らないようにする */
$('input[type=text]').val("")

app/views/chats/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-6">
            <h2>CHAT WITH <%= @user.name %></h2>

            <table class="message table">
              <thead>
                <tr>
                  <th style="text-align: left; font-size: 20px;"><%= current_user.name %></th>
                  <th style="text-align: right; font-size: 20px;"><%= @user.name %></th>
                </tr>
              </thead>
              <% @chats.each do |chat| %>
                <% if chat.user_id == current_user.id %>
                <tbody>
                  <tr>
                    <th>
                      <p style="text-align: left;"><%= chat.message %></p>
                    </th>
                    <th></th>
                  </tr>
                <% else %>
                  <tr>
                    <th></th>
                    <th>
                      <p style="text-align: right;"><%= chat.message %></p>
                    </th>
                  </tr>
                </tbody>
                <% end %>
              <% end %>
            </table>

            <%= form_with model: @chat, remote: true do |f| %>
              <%= f.text_field :message %>
              <%= f.hidden_field :room_id %>
              <%= f.submit "SEND", class:"btn btn-sm btn-success chat-btn" %>
            <% end %>
        </div>
    </div>
</div>

<% if current_user != @user %>
  <%= link_to 'Begin Chat', chat_path(@user.id) %>
<% end %>

app/views/users/_info.html.erb
    <h2>User info</h2>
    <%#= attachment_image_tag user, :profile_image_id, :fill, 50, 50, fallback: "no_image.jpg"%>
    <%= attachment_image_tag user, :profile_image_id, size: "100x100", fallback: "no_image.jpg"%>
    <!--プロフ画像-->
    <table class="table table-hover table-inverse">
      <thead>
    <!--<tr>-->
    <!-- <th>Name</th>-->
    <!--<th><</th>-->
    <!--</tr>-->
    <!--<tr>-->
    <!--<th>Introduction</th>-->
    <!--</tr>-->
      <tbody>
        <tr>

     <th>Name</th>
    <th><%= user.name %></th>
    </tr>
    <tr>
    <th>Introduction</th>
    <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>follows</th>
      <th>
        <%= link_to user.followings.count, user_followings_path(user) %>
      </th>
    </tr>
    <tr>
      <th>followers</th>
      <th><%= link_to user.followers.count, user_followers_path(user) %></th>
    </tr>

    </tbody></table>
    <div>
      <% if current_user != user %>
  　　　　<% if current_user.following?(user) %>
　        <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class:"btn btn-danger" %>
　         <div>
              <!--edit画面-->
              <%= link_to "chat", chats_show_path(user), class: "btn btn-success" %>
              <%#= link_to "chat", chats_show_path(chat.id) %>
            </div>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class:"btn btn-success" %>
        <% end %>
      <% end %>
    </div>



      <div class="row">
        <%= link_to "", edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user" %>
      </div>

app/views/users/_users.html.erb
<table class="table table-sm user-index">
	  	  <h2>Users</h2>
        <thead>
          <th>image</th>
          <th>name</th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
  	    </thead>
  	  	<tbody>
  	  	  <% users.each do |user| %>
	  	  	<tr>
	  	  	  <td><%= attachment_image_tag user, :profile_image_id, size: "100x100",fallback: "no_image.jpg"%></td>
	  	  	  <td><%= user.name %></td>
	  	  	  <td>フォロー数：<%= link_to user.followings.count, user_followings_path(user) %></td>
	  	  	  <td>フォロワー数：<%= link_to user.followers.count, user_followers_path(user) %></td>
	  	  	  <td>
                <% if current_user.following?(user) %>
                  <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
                <% else %>
                  <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                <% end %>
	  	  	  </td>
	  	  	  <td><%= link_to "Show", "/users/#{user.id}" %></td>
	  	  	</tr>
  	  	  <% end %>
  	  	</tbody>
  	  </table>

app/views/users/edit.html.erb
<h1>User info</h1>
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のerrorが発生しました
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_with model:@user, local:true do |f| %>
  <div class="user-name">Name</div>
    <%= f.text_field :name %>
  <div class="user-edit-image">Image</div>
    <%= f.attachment_field :profile_image %>
  <div class="form-body">Introduction</div>
    <%= f.text_area :introduction %>
    <br>
  <div class="upload">
    <%= f.submit " Update User" %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
      <%= render 'books/newbook', book: @book %>
    </div>
   <div class="col-md-8 offset-md-1">
  	  <table class="table table-sm user-index">
	  	  <h2>Users</h2>
        <thead>
          <th>image</th>
          <th>name</th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
  	    </thead>
  	  	<tbody>
  	  	  <% @users.each do |user| %>
	  	  	<tr>
	  	  	  <td><%= attachment_image_tag user, :profile_image_id, size: "100x100",fallback: "no_image.jpg"%></td>
	  	  	  <td><%= user.name %></td>
	  	  	  <td>フォロー数：<%= link_to user.followings.count, user_followings_path(user) %></td>
	  	  	  <td>フォロワー数：<%= link_to user.followers.count, user_followers_path(user) %></td>
	  	  	  <td>
	  	  	    <% if current_user != user %>
                <% if current_user.following?(user) %>
                  <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
                <% else %>
                  <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                <% end %>
              <% end %>
	  	  	  </td>
	  	  	  <td><%= link_to "Show", "/users/#{user.id}" %></td>
	  	  	</tr>
  	  	  <% end %>
  	  	</tbody>
  	  </table>
   </div>
 </div>
</div>

app/views/users/search.html.erb
<%= form_with(url: user_search_path(current_user.books), local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">


    <%= render partial: "users/users", locals: { users: @users } %>

</div>

app/views/users/show.html.erb
<%#= flash[:notice] %>
<div class="container">
 <div class="row">
   <div class="col-md-3">
       <%= render 'users/info', user: @user %>
       <%= render 'books/newbook', book: @book %>
    </div>
     <div class="col-md-8 offset-md-1">
       <h2>Books</h2>
       <table class="table table-hover table-inverse">
     <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
     <% @books.each do |book| %>
        <tr>
            <td>
             <%= link_to user_path(book.user) do %>
             <%= attachment_image_tag book.user, :profile_image_id, size: "50x50",fallback: "no_image.jpg"%>
             <% end %>
             </td>
         <td><%= link_to book.title, book_path(book.id) %></td>
         <td><%= book.body %></td>
         <td id ="favorite_botton_<%= book.id %>" >
             <%= render partial: "favorites/favorites", locals: { book: book } %>
         </td>
         <td><%= link_to "コメント数: #{book.book_comments.count}", book_path(book.id) %></td>
       </tr>
       <% end %>
        </tbody>
     </table>
   </div>
 </div>
</div>