config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'users/show'
  devise_for :users
  root to: 'homes#top'
  get "home/about" => "homes#about"
  get "search" => "searchs#search"
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]

   resources :books, only: [:new, :create, :index, :show, :destroy, :update, :edit] do
       resource :favorites, only: [:create, :destroy]
       resources :book_comments, only: [:create, :destroy]
    #   get 'search'
   end

   resources :users, only: [:index, :show, :edit, :update, :create] do
        resource :relationships, only: [:create, :destroy]
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
        # get 'search' => 'users#search'
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
   belongs_to :user, optional: true
   has_many :book_comments, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :favorited_users, through: :favorites, source: :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  is_impressionable counter_cache: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


  def self.search(search)
    if search
      Book.where('title LIKE(?)', "%#{search}%")
    #   Book.where('title LIKE(?)', 'body LIKE(?)', "%#{search}%")
    else
      Book.all
    end
  end


end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end
# a

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms  #1つのルームにいるユーザ数は2人のためhas_manyになる
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
   has_many :favorited_books, through: :favorites, source: :book

 has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
 has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人
 has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
 has_many :followings, through: :relationships, source: :followed

 has_many :user_rooms, dependent: :destroy
 has_many :chats, dependent: :destroy
  # ここから下↓はもしかしたらいらんかも↓
    def follow(user_id)
      relationships.create(followed_id: user_id)
    end

    def unfollow(user_id)
      relationships.find_by(followed_id: user_id).destroy
    end

    def following?(user)
      followings.include?(user)
    end

# ↓これ多分使わんから消していい
    # ユーザーをフォローする
# def follow(user_id)
#   follower.create(followed_id: user_id)
# end

# # ユーザーのフォローを外す
# def unfollow(user_id)
#   follower.find_by(followed_id: user_id).destroy
# end

# フォローしていればtrueを返す
# def following?(user)
#   followings.include?(user)
# end
 # ここまでいらんやつかも

 def self.search(search)
    if search
      User.where('name LIKE(?)', "%#{search}%")
    else
      User.all
    end
 end


  attachment :profile_image

  validates :name, presence: true, length: { minimum: 2,  maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
end

app/models/user_list.rb
class UserList < ApplicationRecord
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    # 回答にあった記載↓
    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day
    # @books = Book.includes(:favorited_users).sort {|a,b| b.favorited_users.where(created_at: from...to).size <=> a.favorited_users.where(created_at: from...to).size }
    @books = Book.includes(:favorited_users).sort {|a,b| b.favorited_users.where(created_at: from...to).size <=> a.favorited_users.where(created_at: from...to).size}
    # これやと並び替えはできる
    # ってことはここに「過去１週間のデータで」って入れられたらうまくいく？？

# 余裕できたら応用課題の質問する

    @user = current_user
    @book = Book.new
    # @ranks = Book.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}

  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    # @users = User.all
    @newbook = Book.new
    @book_comment = BookComment.new
    @comments = @book.book_comments
    # impressionist(@book, nil, unique: [:ip_address])
  end

  def new
    @book = Book.new
  end

  def create
     @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="You have creatad book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body,:impressions_count)
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

 def show
  @user = User.find(params[:id])
  rooms = current_user.user_rooms.pluck(:room_id)
  user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

  if user_rooms.nil?
   @room = Room.new
   @room.save
   UserRoom.create(user_id: @user.id, room_id: @room.id)
   UserRoom.create(user_id: current_user.id, room_id: @room.id)
  else
   @room = user_rooms.room
  end

  @chats = @room.chats
  @chat = Chat.new(room_id: @room.id)
 end

 def create
  @chat = current_user.chats.new(chat_params)
  @chat.save
 end

 private

 def chat_params
  params.require(:chat).permit(:message, :room_id)
 end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Bookers2</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

     <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
       <div class="container">
       <a class="navbar-brand" href="/"><span>Bookers</span></a>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
       </button>
         <div class="collapse navbar-collapse" id="navbarNavDropdown">
         <% if user_signed_in? %>
           <ul class="navbar-nav ml-auto">
            <li>
              <%= link_to user_path(current_user), class:"btn btn-link" do %>
              <span class="fas fa-home nav-link text-light" aria-hidden="true"> Home</span>
              <% end %>
            </li>
            <li>
              <%= link_to users_path, class:"btn btn-link" do %>
              <span class="fas fa-users nav-link text-light" aria-hidden="true"> Users</span>
              <% end %>
              </li>
            <li>
              <!--<a class="" href="/books"> Books</a>-->
              <%= link_to books_path, class:"btn btn-link" do %>
              <span class="fas fa-book-open nav-link text-light" aria-hidden="true"> Books</span>
              <% end %>
              </li>
            <li>
              <!--<a class="fas fa-sign-out-alt nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out"></a>-->
              <%= link_to destroy_user_session_path, method: :delete, class:"btn btn-link" do %>
              <span class="fas fa-sign-out-alt nav-link text-light" aria-hidden="true"> logout</span>
              <% end %>
              </li>
          </ul>
              <%= render "searchs/form" %>

        <% else %>
         <ul class="navbar-nav ml-auto">
            <li>
              <!--<a class="" href="/"> Home</a>-->
              <%= link_to root_path, class:"btn btn-link" do %>
              <span class="fas fa-home nav-link text-light" aria-hidden="true"> Home</span>
              <% end %>
            </li>
            <li>
              <!--<a class="fas fa-link nav-link text-light" href="home/about"> About</a>-->
              <%= link_to home_about_path, class:"btn btn-link" do %>
              <span class="fas fa-link nav-link text-light" aria-hidden="true"> About</span>
              <% end %>
              </li>
            <li>
              <!--<a class="fas fa-user-plus nav-link text-light" href="/users/sign_up"> sign up</a>-->
              <%= link_to new_user_registration_path, class:"btn btn-link" do %>
              <span class="fas fa-user-plus nav-link text-light" aria-hidden="true"> sign up</span>
              <% end %>
              </li>
            <li>
            <!--<a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in"> login</a>-->
            <%= link_to new_user_session_path, class:"btn btn-link" do %>
              <span class="fas fa-sign-in-alt nav-link text-light" aria-hidden="true"> login</span>
              <% end %>
              </li>
        <% end %>
      </div>
    </div>
      </nav>
    </header>
  <p class="notice"><%= notice %></p>
<%= yield %>
  <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
</html>